Implemented 5 tests on Report Portal.
jdi-examples/jdi-light-report-portal-demo pull request #3
Opened 2020-06-01 17:57 UTC by gbuh

2020-06-01 18:04 UTC, AkioFaris commented
[19] - c0Mua3f4

2020-06-01 18:06 UTC, AkioFaris commented
[19] - Allure report on Netlify: https://5ed5439f7ee67edd1bbfdd61--thirsty-yalow-da011e.netlify.app

2020-06-02 07:17 UTC, AkioFaris commented
Please change the suite name (currently it's shown as "JDI-Light Bootstrap Tests" in Allure report)

2020-06-02 07:27 UTC, AkioFaris requested changes
1. Resolve comments
2. Please change the suite name (currently it's shown as "JDI-Light Bootstrap Tests" in Allure report)
3. Test should pass in Allure report and on Jenkins (add a link to a passed run in Jenkins)

2020-06-02 07:27 UTC, AkioFaris commented on src/test/java/io/github/epam/test/data/UserUtils.java
> +        u.userName = "default";
Remove user's credentials from the code. 
They are passed as command line parameters of the Maven command: "mvn test -Dreport.portal.user=$TEST_USER_LOGIN -Dreport.portal.password=$TEST_USER_PASSWORD" (see travis.yml to understand current Travis CI build)

2020-06-02 07:27 UTC, AkioFaris commented on src/test/java/io/github/epam/tests/LoginTest.java
> +        userName.assertThat().text(DEFAULT_USER.userName.toUpperCase());
Use System.getProperty("report.portal.user") to get expected username

2020-06-02 08:27 UTC, gbuh commented
> 1. Resolve comments
> 2. Please change the suite name (currently it's shown as "JDI-Light Bootstrap Tests" in Allure report)
> 3. Test should pass in Allure report and on Jenkins (add a link to a passed run in Jenkins)

Resolved. Please look into it.

2020-06-02 08:31 UTC, AkioFaris commented
[20] - DRHifCsa

2020-06-02 08:34 UTC, AkioFaris commented
[20] - Allure report on Netlify: https://5ed60f1764600d45ecd3efa4--thirsty-yalow-da011e.netlify.app

2020-06-02 08:59 UTC, AkioFaris commented
[21] - BxtfmzRK

2020-06-02 09:01 UTC, AkioFaris commented
[21] - Allure report on Netlify: https://5ed6154c661e51677220a59d--thirsty-yalow-da011e.netlify.app

2020-06-02 09:01 UTC, AkioFaris commented
[22] - EBQh36aE

2020-06-02 09:03 UTC, AkioFaris commented
[22] - Allure report on Netlify: https://5ed615e56afa3c83fb941f0a--thirsty-yalow-da011e.netlify.app

2020-06-02 12:49 UTC, AkioFaris commented
[23] - dmFV4gCt

2020-06-02 12:52 UTC, AkioFaris commented
[23] - Allure report on Netlify: https://5ed64b73b63fa95f6886df76--thirsty-yalow-da011e.netlify.app

2020-06-02 19:04 UTC, AkioFaris commented
[24] - ZGKY5D4Y

2020-06-02 19:06 UTC, AkioFaris commented
[24] - Allure report on Netlify: https://5ed6a319b1af4b3f393ff33e--thirsty-yalow-da011e.netlify.app

2020-06-03 10:09 UTC, AkioFaris commented
[25] - NEIE9HOf

2020-06-03 10:11 UTC, AkioFaris commented
[25] - Allure report on Netlify: https://5ed7773cf9a9bc302f431b3b--thirsty-yalow-da011e.netlify.app

2020-06-03 19:12 UTC, AkioFaris commented
[26] - pKeh5EWS

2020-06-03 19:15 UTC, AkioFaris commented
[26] - Allure report on Netlify: https://5ed7f6b905d93879f2ff6649--thirsty-yalow-da011e.netlify.app

2020-06-04 08:32 UTC, AkioFaris commented
[27] - 3R9PevQS

2020-06-04 08:34 UTC, AkioFaris commented
[27] - Allure report on Netlify: https://5ed8b2146616f7a6ded83f88--thirsty-yalow-da011e.netlify.app

2020-06-04 09:28 UTC, AkioFaris commented
[28] - mjsienkd

2020-06-04 09:30 UTC, AkioFaris commented
[28] - Allure report on Netlify: https://5ed8bf4fc44f696bc1622700--thirsty-yalow-da011e.netlify.app

2020-06-04 13:26 UTC, AkioFaris requested changes
See comments

2020-06-04 13:26 UTC, AkioFaris commented on src/main/java/io/github/com/entities/User.java
> +    //    public String userName = "test-user";
Please remove user creds from the code

2020-06-04 13:26 UTC, AkioFaris commented on src/main/java/io/github/com/entities/User.java
> +    public String userName = System.getProperty("report.portal.user");
Maybe add 2 constructors (with and without parameters)

2020-06-04 16:22 UTC, AkioFaris commented
[29] - Q4oFVGR2

2020-06-04 16:23 UTC, gbuh commented on src/main/java/io/github/com/entities/User.java
> +    public String userName = System.getProperty("report.portal.user");
Done

2020-06-04 16:24 UTC, gbuh commented on src/main/java/io/github/com/entities/User.java
> +    //    public String userName = "test-user";
Done

2020-06-04 16:25 UTC, AkioFaris commented
[29] - Allure report on Netlify: https://5ed92066c29f75c3dc6457bb--thirsty-yalow-da011e.netlify.app

2020-06-05 08:25 UTC, AkioFaris approved these changes

2020-06-05 09:30 UTC, AkioFaris approved these changes

2020-06-05 09:35 UTC, AkioFaris commented
[31] - sfKJJxig

2020-06-05 09:37 UTC, AkioFaris commented
[31] - Allure report on Netlify: https://5eda12734873ef867bc25ce4--thirsty-yalow-da011e.netlify.app

2020-06-05 09:51 UTC, AkioFaris commented
[32] - 2YnylCEC

2020-06-05 09:53 UTC, AkioFaris commented
[32] - Allure report on Netlify: https://5eda16027f8e20bd6bd9da09--thirsty-yalow-da011e.netlify.app

2020-06-05 17:17 UTC, merged